repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.2
    hooks:
      - id: ruff # Run the linter.
        name: Run Linter Check (Ruff)
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
        files: ^(src|tests|examples)/
      - id: ruff-format # Run the formatter.
        name: Run Formatter (Ruff)
        types_or: [ python, pyi, jupyter ]
        files: ^(src|tests|examples)/
